insert into drug_company (name, country) values ('Golden State Medical Supply, Inc.', 'Belarus');
insert into drug_company (name, country) values ('Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', 'Brazil');
insert into drug_company (name, country) values ('Bare Escentuals Beauty Inc.', 'Philippines');
insert into drug_company (name, country) values ('Clinical Solutions Wholesale', 'Madagascar');
insert into drug_company (name, country) values ('Unit Dose Services', 'Russia');
insert into drug_company (name, country) values ('Mallinckrodt, Inc.', 'Russia');
insert into drug_company (name, country) values ('Cardinal Health', 'Argentina');
insert into drug_company (name, country) values ('Sanum Kehlbeck GmbH & Co. KG', 'Poland');
insert into drug_company (name, country) values ('Save-A-Lot Food Stores Ltd', 'Mexico');
insert into drug_company (name, country) values ('Energique, Inc.', 'China');
insert into drug_company (name, country) values ('AMOREPACIFIC', 'Sweden');
insert into drug_company (name, country) values ('A&Z Pharmaceutical, Inc.', 'Canada');
insert into drug_company (name, country) values ('Hospira, Inc.', 'France');
insert into drug_company (name, country) values ('Nelco Laboratories, Inc.', 'Brazil');
insert into drug_company (name, country) values ('Publix Super Markets Inc', 'Nigeria');
insert into drug_company (name, country) values ('Chain Drug Marketing Association', 'Tanzania');
insert into drug_company (name, country) values ('Physicians Total Care, Inc.', 'Malaysia');
insert into drug_company (name, country) values ('RxPak Division of McKesson Corporation', 'China');
insert into drug_company (name, country) values ('Cardinal Health', 'Honduras');
insert into drug_company (name, country) values ('McKesson Packaging Services a business unit of McKesson Corporation', 'China');
insert into drug_company (name, country) values ('Lake Erie Medical DBA Quality Care Products LLC', 'Portugal');
insert into drug_company (name, country) values ('SUPERVALU INC.', 'Brazil');
insert into drug_company (name, country) values ('Kay Chemical Company', 'China');
insert into drug_company (name, country) values ('Greenstone LLC', 'Portugal');
insert into drug_company (name, country) values ('Meijer Distribution Inc', 'Czech Republic');
