SELECT DISTINCT IF(C.CUST_TYPE_CD="I", CONCAT(I.FNAME, ' ', I.LNAME), B.NAME) AS NAMES
FROM CUSTOMER C
LEFT JOIN INDIVIDUAL I ON C.CUST_ID=I.CUST_ID
LEFT JOIN BUSINESS B ON C.CUST_ID=B.CUST_ID
INNER JOIN ACCOUNT A ON A.CUST_ID=C.CUST_ID
INNER JOIN BRANCH BR ON BR.BRANCH_ID=A.OPEN_BRANCH_ID
WHERE BR.CITY != C.CITY;