SELECT DISTINCT CONCAT(I.FNAME, ' ', I.LNAME)
FROM CUSTOMER C 
INNER JOIN INDIVIDUAL I ON C.CUST_ID = I.CUST_ID
INNER JOIN ACCOUNT A ON A.CUST_ID = C.CUST_ID
INNER JOIN BRANCH BR ON BR.BRANCH_ID = A.OPEN_BRANCH_ID
WHERE BR.CITY != C.CITY
UNION
SELECT DISTINCT B.NAME
FROM CUSTOMER C 
INNER JOIN BUSINESS B ON C.CUST_ID = B.CUST_ID
INNER JOIN ACCOUNT A ON A.CUST_ID = C.CUST_ID
INNER JOIN BRANCH BR ON BR.BRANCH_ID = A.OPEN_BRANCH_ID
WHERE BR.CITY != C.CITY;
-- Marco Antonio Faustini Pessoa