SELECT CONCAT(E.FNAME, ' ', E.LNAME) AS NOME, YEAR(T.TXN_DATE), COUNT(T.TXN_ID)
FROM EMPLOYEE E LEFT JOIN ACCOUNT A ON E.EMP_ID = A.OPEN_EMP_ID
LEFT JOIN TRANSACTION T ON A.ACCOUNT_ID = T.ACCOUNT_ID
GROUP BY E.EMP_ID, NOME, YEAR(T.TXN_DATE)
ORDER BY NOME, YEAR(TXN_DATE);