CREATE SCHEMA restaurante;
USE restaurante;
CREATE TABLE CLIENTE(
idCliente INT PRIMARY KEY,
cpf VARCHAR(14),
nome VARCHAR(150),
rua VARCHAR(150),
numero INT,
bairro VARCHAR(50));
CREATE TABLE ATENDENTE(
matricula INT(3) ZEROFILL PRIMARY KEY,
nome VARCHAR(150) NOT NULL,
salario FLOAT NOT NULL,
responsavel INT(3) ZEROFILL,
CONSTRAINT ATEN_ATEN FOREIGN KEY (responsavel) REFERENCES ATENDENTE(matricula));
CREATE TABLE CONTATO_ATENDENTE(
idAtendente INT(3) ZEROFILL NOT NULL,
telefone VARCHAR(15) NOT NULL,
PRIMARY KEY (idAtendente, telefone),
CONSTRAINT CON_ATEN FOREIGN KEY (idAtendente) REFERENCES ATENDENTE(matricula));
CREATE TABLE ITEM(
codigo INT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
preco FLOAT NOT NULL,
tipo ENUM("Prato", "Bebida"));
CREATE TABLE MESA(
numero INT(2) ZEROFILL PRIMARY KEY);
CREATE TABLE PEDIDO(
idPedido INT AUTO_INCREMENT PRIMARY KEY,
inicio TIMESTAMP NOT NULL,
fim TIMESTAMP NOT NULL,
duracao TIMESTAMP NOT NULL,
atendente INT(3) ZEROFILL NOT NULL,
cliente INT NOT NULL,
mesa INT(2) ZEROFILL NOT NULL,
CONSTRAINT PED_ATEN FOREIGN KEY (atendente) REFERENCES ATENDENTE(matricula),
CONSTRAINT PED_CLI FOREIGN KEY (cliente) REFERENCES CLIENTE(idCliente),
CONSTRAINT PED_MESA FOREIGN KEY (mesa) REFERENCES MESA(numero));
CREATE TABLE PEDIDO_HAS_ITENS(
idPedido INT AUTO_INCREMENT NOT NULL,
idItem INT NOT NULL,
PRIMARY KEY (idPedido, idItem),
CONSTRAINT PED_PED FOREIGN KEY (idPedido) REFERENCES PEDIDO(idPedido),
CONSTRAINT PED_ITEM FOREIGN KEY (idItem) REFERENCES ITEM(codigo));